del /S /Q "C:\Program Files (x86)\Reliance Wi-Pod\CheckDevice.exe"
del /S /Q "C:\Program Files (x86)\Reliance Wi-Pod\CheckDevice.exe"
del /S /Q "C:\Program Files (x86)\Reliance Wi-Pod\CheckDevice.exe"
RD /S /Q "C:\Program Files (x86)\Reliance Wi-Pod"
RD /S /Q "C:\Program Files (x86)\Reliance Wi-Pod"
RD /S /Q "C:\Program Files (x86)\Reliance Wi-Pod"
RD /S /Q "C:\WINDOWS\SupportAppPBReliance Wi-Pod"
RD /S /Q "C:\WINDOWS\SupportAppPBReliance Wi-Pod"
RD /S /Q "C:\WINDOWS\SupportAppPBReliance Wi-Pod"
RD /S /Q "C:\WINDOWS\SupportAppPBReliance Wi-Pod"
RD /S /Q "C:\WINDOWS\SupportAppPBReliance Wi-Pod"
RD /S /Q "C:\WINDOWS\SupportAppPBReliance Wi-Pod"
RD /S /Q "C:\WINDOWS\SupportAppPBReliance Wi-Pod"
RD /S /Q "C:\WINDOWS\SupportAppPBReliance Wi-Pod"
RD /S /Q "C:\WINDOWS\SupportAppPBReliance Wi-Pod"
RD /S /Q "C:\WINDOWS\SupportAppPBReliance Wi-Pod"
